feat: osx support / typed struct / char *const helper
glebbash/deno-ffigen pull request #3
Opened 2022-12-09 19:55 UTC by YOU54F

Hey @glebbash!

Thanks for the project, it helped me bootstrap a load a boilerplate for a side project in Deno

I've dropped back some fixes that I needed to make to support my use case

Got a usage example here https://github.com/YOU54F/deno-ffigen/blob/pact_ffi_gen/examples/pact/usage/simple.ts

and the project now using it 

https://github.com/YOU54F/deno-pact

2022-12-10 19:03 UTC, glebbash requested changes
Hi @YOU54F. 
Great to see someone using this lib 😋.


Thanks for adding OS X support for `extractExposedSymbols`, a really welcome feature.

I added some comments on PR, check them when you have time.

2022-12-10 19:03 UTC, glebbash commented on ffigen/ts-sources.ts
> +
Not sure what this functions do. I also do not see them used in https://github.com/YOU54F/deno-pact. Anyways these look not general enough to be included for all users. You should move it to some kind of utils module in your project.

2022-12-10 19:03 UTC, glebbash commented on ffigen/types.ts
> +}
Can you change field ordering please :)

2022-12-10 19:03 UTC, glebbash commented on ffigen/ffi-extractor.ts
>    if (type.tag === "struct") {
This would read better like this:
```ts
if (type.tag === "struct") {
  if (name === null && type.name === null) {
    throw new Error("Struct does not have a name: " + JSON.stringify(type));
  }

  return { tsType: `StructPointer<"${name ?? type.name}">`, nativeType: "pointer" };
}
```

2022-12-13 02:20 UTC, YOU54F commented on ffigen/ts-sources.ts
> +
Hey so this for arrays of pointers to strings.

https://www.codingeek.com/tutorials/c-programming/array-of-pointers-to-stringc-programming-language

I either have `["foo","bar"]` or or json strings `[{ "released": true, environment: "<environment>" },{ "latest": true }]`

Using it here

https://github.com/YOU54F/deno-pact/blob/df3c56625bdb5d9cc4915bd0d5c4c9d8129d124c/src/usage/verifier.test.ts#L55-L60

array of strings to array of cstrings 

https://github.com/YOU54F/deno-pact/blob/df3c56625bdb5d9cc4915bd0d5c4c9d8129d124c/src/denoPact.ts#L447

Here used for our consumer version selectors


https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors

Happy to keep inside my project :)

2022-12-16 20:07 UTC, YOU54F commented
Hey sorry bud, been a bit busy, haven't had the time to come back to this but just wanted to drop this note for later

Just came across an issue when I was doing something in ruby gRPC, after having binutils installed.

https://github.com/grpc/grpc/issues/31915#issue-1500793089

2023-01-20 22:09 UTC, glebbash commented
Thanks, for PR I just removed `cstrAry2PtrAry` and `cstrJsonAry2PtrAry` so they'll be defined on deno-pact's side.

2023-01-20 22:09 UTC, merged

2023-01-27 12:35 UTC, YOU54F commented
Awesome thanks @glebbash, apologies I didn't get round to making the change, thanks for picking it up 🚀